### ISSUE TITLE
8-entry Finger Table

### ISSUE THREAD

**Issue by Jetszxcki** [ChuanXia/Chord#2]

**Comment by ChuanXia** [comment]
Sure thing. Do you want check in to master?

**Comment by Jetszxcki** [comment]
Yes please :D

**Comment by Jetszxcki** [comment]
Sorry let me re-state the question. Can your implementation be modified to an 8-entry finger table only?

**Comment by ChuanXia** [comment]
Are you going to use it for school project? If so, you can fork this repo
and change it in yours.
If you think it’s going to make the original repo better in some way, can
you elaborate more on the improvement? Then you can make a pull request.

**Comment by Jetszxcki** [comment]
Yes for a school project. But our implementation only needs to have an 8 entry finger table with a maximum of 128 nodes in the chord.

**Comment by Jetszxcki** [comment]
What specific file do I need to change to set it to only 8 entries finger table?

**Comment by ChuanXia** [comment]
You’ll need to change Node.java. In your case, it’s better to fork and
change in your own repo because it’s specific to your school project.

**Comment by Jetszxcki** [comment]
Yes, I will not modify master. Thanks!
